### ISSUE TITLE
performance - saveMessage crazy slow

### ISSUE THREAD

**Issue by tvogt** [FriendsOfSymfony/FOSMessageBundle#112]
I'm hunting performance issues in my code and I've found that this call:

        $this->messageManager->saveMessage($message);

in Sender.php, method send is sometimes taking several SECONDS. I'm measuring the time between the line right before and the one right after:

 $sub_start = microtime(true);
 $this->messageManager->saveMessage($message);
 $t = (microtime(true)-$sub_start); if ($t>0.02) echo("  - saveMessage 2: $t s\n");

Something very strange is going on. In 7 seconds I should be able to save a hundred messages, not one.

**Comment by tgalopin** [comment]
That's something we have to keep in mind for the new version. I close this.

**Comment by tvogt** [comment]
What toinouu writes could be correct, I have some big topics with > 100 users reading and > 200 messages in them. If it iterates over something there, it could take a while.

**Comment by tgalopin** [comment]
In the new version, the links between conversations and users will be the objects storing the read / new status, so I think the problem will be solved.
