### ISSUE TITLE
Adding behat features

### ISSUE THREAD

**Issue by khepin** [FriendsOfSymfony/FOSMessageBundle#117]
This bundle is currently lacking any form of validation that it is working as expected.
Be it tests, BDD or others.

I'm trying to setup behat so that at least we can specify and verify the outside behavior of the bundle here: ( https://github.com/khepin/FOSMessageBundle/tree/behat ).

I'm now blocked because (it seems) of some configuration in the security bundle:

```
PHP Fatal error:  Call to undefined method Symfony\Component\Config\Definition\Builder\NodeBuilder::integerNode() in /home/seb/projects/FOSMessageBundle/vendor/symfony/security-bundle/Symfony/Bundle/SecurityBundle/DependencyInjection/MainConfiguration.php on line 386
```

Any help in getting me started will be greatly appreciated here.

You can checkout this branch, then run `composer install --dev`. After this is done run `./vendors/bin/behat` that's as far as I could go for now.

**Comment by tgalopin** [comment]
@khepin A new version is currently in development, are you interested in working on Behat / BDD tests? I planned unit and functionnal tests, but BDD could be interesting.
