### ISSUE TITLE
recipients validation + no setRecipients method

### ISSUE THREAD

**Issue by rat4m3n** [FriendsOfSymfony/FOSMessageBundle#134]
Class FOS\MessageBundle\FormModel\NewThreadMultipleMessage

There is no validation kicking in for recipients and no setRecipients method set so we end up with nasty error

> Property "recipients" is not public in class "FOS\MessageBundle\FormModel\NewThreadMultipleMessage". Maybe you should create the method "setRecipients()"?

**Comment by tgalopin** [comment]
I close this as it's old, but if someone still have the problem, please tell me.
