### ISSUE TITLE
Must be logged in with a ParticipantInterface instance

### ISSUE THREAD

**Issue by EwanValentine** [FriendsOfSymfony/FOSMessageBundle#146]
I'm attempting to use FOSMessageBundle with FOSUserBundle and I'm getting this, I've tried implementing ParticipantInterface on the User entity and that's not worked, I've tried another few bits, but have had no luck as of yet, any suggestions?

**Comment by tgalopin** [comment]
I assume you find your answer @EwanValentine I close this.

**Comment by EwanValentine** [comment]
Apologies, yes please close. Thanks again.
