### ISSUE TITLE
Slice messages of a thread

### ISSUE THREAD

**Issue by maxpowel** [FriendsOfSymfony/FOSMessageBundle#155]
Hi!

My intention is show the las 10 messages of a thread (as previsualization) because my threads have a lo of messages.

I would like to avoid load the full message list and then splice the array in PHP. Is there any way to set an offset and size when getting messages from a thread?
The method getMessages() returns a populated array (doctrine ArrayCollection would be perfect)

Thank you

**Comment by bbtdigitalkaran** [comment]
Does anyone have a concrete solution to this yet?

**Comment by tgalopin** [comment]
You can create your own specific query without using the bundle (directly on the documents). However, for the moment, with the bundle tools, there is no other solution than loading all the messages and slicing the array.

This bundle is not currently maintained (I could become the new maintainer soon: https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/54) so there will likely be no solution in the bundle before a few weeks. If I become the maintainer, I'll try to see if it's possible easily without breaking BC.

**Comment by hex333ham** [comment]
@tgalopin was this ever resolved?

**Comment by hex333ham** [comment]
regardless, this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
