### ISSUE TITLE
Unread messages in a thread

### ISSUE THREAD

**Issue by maxpowel** [FriendsOfSymfony/FOSMessageBundle#160]
Hi!

I'm trying to get the number of unread messages in a thread. The reason is to display a list of threads with new messages and the number of new messages of every thread.

Anyone did something like that? I'm trying to avoid raw queries (I'm using orm)

The only thing I found is https://github.com/FriendsOfSymfony/FOSMessageBundle/pull/106 but it is not available yet

Thank you

**Comment by smilesrg** [comment]
@merk is that PR has been accepted?
