### ISSUE TITLE
Allow sender to be null

### ISSUE THREAD

**Issue by yakobe** [FriendsOfSymfony/FOSMessageBundle#163]
It should be possible to have no sender for messages (either by not setting it or setting it to null) so that we can allow notifications to a user's inbox. This would bring notification messages and user2user messages in one place.
It should not be possible to reply to these messages.
I realise that i can add a dummy user, but that is a dirty solution. 
I know that some people have mentioned this but i really think it would be a useful feature.

**Comment by tgalopin** [comment]
The new library and bundle will be more generic than the current version so you will be able to use it this way if you want.
