### ISSUE TITLE
Bundle is dependent on FOSUserBundle

### ISSUE THREAD

**Issue by Gadgetdude** [FriendsOfSymfony/FOSMessageBundle#206]
In a previous commit the user_transformer was added. The scalar node cannot be empty and refers to FOSUserBundle. In the composer file FOSUserBundle is not given as a required dependency.

Since not everybody is using FOSUserBundle, this reference should be made optional in the config tree builder and added to the recommended list in composer file. Or maybe another solution?

**Comment by tgalopin** [comment]
I just updated the documentation to explain how to not depend on FOSUserBundle: https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/99-using-other-user-bundles.md.
