### ISSUE TITLE
message does not appear in inbox, if sender == recipient

### ISSUE THREAD

**Issue by andrejsramko** [FriendsOfSymfony/FOSMessageBundle#213]
If you create a message in the default form, it is validated wheather sender == recipient and "You cannot send a message to yourself" message appears.

However, if you send the message "manually" from a controller with
```
$threadBuilder->addRecipient($user)
              ->setSender($user)
              ->setSubject($subject)
              ->setBody($body);
```
only one DB entry in threadmetadata with last_message_date = NULL is created, which causes, that the message can be seen in the "sent messages" folder and does not appear in "inbox"

**Comment by archie18** [comment]
I encountered the same problem. I would like to use the super admin user account to send automatic system messages to the same super admin account. But this is currently NOT possible.

**Comment by tgalopin** [comment]
It will be possible in the next version we are working on (a complete rewrite) as it will be much more generic than the current bundle. I close this issue as we won't implement it in this version.
