### ISSUE TITLE
Using this bundle from another framework

### ISSUE THREAD

**Issue by ojhaujjwal** [FriendsOfSymfony/FOSMessageBundle#218]
The title says it all. I think it is possible. The requirements are not much as listed in composer.json.

I have an application already developed with Zend framework 2 and I want to add messaging feature to the application. Is it possible to use this bundle?

A solution would be to split this bundle to a component just like Sylius has done recently. But, that will be a lot of work and a big BC break.

But, I think it can be done without splitting it to component.

**Comment by tgalopin** [comment]
This will be answered by the new version as the bundle will only be a specific implementation of the library.

**Comment by tgalopin** [comment]
@ojhaujjwal If you want to give a hand for the library, I'll work there: https://github.com/FriendsOfSymfony/FOSMessage

**Comment by ojhaujjwal** [comment]
@tgalopin Thanks for letting me know. I am interested in the component and I will try to be involved in it in any way I can :D I will start by watching the repo.

**Comment by tgalopin** [comment]
@ojhaujjwal Awesome, thanks! The first thing you can easily do to give a hand right now is to give your opinion about the [Usage ideas of the library](https://github.com/FriendsOfSymfony/FOSMessage#usage-ideas): would it fit your needs? Do you see missing features? Do you have other ideas?
