### ISSUE TITLE
Permanently Delete a Thread

### ISSUE THREAD

**Issue by monkeyfunky** [FriendsOfSymfony/FOSMessageBundle#220]
Is there a way to permanently (soft delete) a thread so that a user will not see it in their deleted box even though it may still exist in other locations?

**Comment by thegeekrv** [comment]
That would be a great idea ! For me, now that users have threads, i cannot delete them without wasting hours to delete one by one all constraints :/

**Comment by tgalopin** [comment]
I'll see if it's easy to implement in the current version. It will be implemented in the new version.
