### ISSUE TITLE
No active maintainer

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/FOSMessageBundle#229]
We are seeking someone who would like to assist in general maintenance of this bundle, triaging tickets and assisting in reviewing and okaying PRs.

**Comment by eaxfr** [comment]
Hi,
I think this project is dead :/
Is there any other repo or fork to replace this one?

**Comment by tgalopin** [comment]
I agree to change things but I think changing maintainer would be better than forking. The problem with forking is that we would lose the "renown" of FOS and the MessageBundle.

**Comment by redayoub** [comment]
+1 for changing the maintainer

**Comment by tgalopin** [comment]
The thing is we need a current maintainer to change. Is there anyone reading? Is the bundle really dead?

**Comment by merk** [comment]
The trouble is the current FOS members dont have time to maintain this bundle (and probably arent using it).

Ultimately, to become promoted to maintainer we'd want to see some activity: forking and merging outstanding PRs or making improvements would indicate this - then that code could be merged back here.

My opinion is that we dont want to keep appointing maintainers who will disappear again.

**Comment by AlexGodard** [comment]
Just dropping here to mention I planned on using this bundle. So changes would be appreciated yes! Is   the current version a working one ?

**Comment by tgalopin** [comment]
@merk So should we fork it and work on it on our own then? I'm using this bundle pretty regularly and some ideas as making a library as a base of the bundle are great ideas IMO. There are a lot of things to do :) .

I agree we don't want temoporary maintainers, but for the moment the bundle does not evolve at all, so even a bit of dynamic would be great.

**Comment by merk** [comment]
My suggestion at this point would be to fork the bundle, work on your fork for some time making changes you think would improve the bundle and propose to become the maintainer linking to your work - that means your work can be merged into a new major release of the bundle here.

Alternatively, sending PRs that fix peoples issues or add new functionality and pinging me or @zocimek and in the short term we can merge them.

My personal approach here would be to add some functional testing because there is very little of that in the bundle.

**Comment by tgalopin** [comment]
I forked the bundle and I'll start to work on it there: https://github.com/tgalopin/FOSMessageBundle

However, on the main repo, some issues could be closed such as:

- https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/256 (he is right btw, we should change this) ;
- https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/261 (resolved)
- https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/36 (old)
- https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/112 (old)
- https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/117 (old and resolved I guess)
- https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/153 (old)

Perhaps now is the moment to think of a new version of the bundle based on the current one concepts but using a framework independant library. I think it could be a great project but such a changement require motivated people. Are there motivated people here ready to give a hand (for the library, the bundle would be very light)?

**Comment by redayoub** [comment]
@tgalopin I'm interested, what kind of help do you need?

**Comment by tgalopin** [comment]
The kind of help to rewrite the bundle as a library :) 

I think the steps would be:

1. Isolate the concepts of the current bundle and what we want to do in general
2. Implement the basis of the library using these concepts
3. Discuss more on what we want to add as feature

I started a repository here to discuss the library: https://github.com/tgalopin/FOSMessage
I think we should have the discussions in the issues of this repo (https://github.com/tgalopin/FOSMessage/issues).

So the main and first step for the moment is to review all the features the current bundle have and what we want to add / remove to these features. I started a discussion here: https://github.com/tgalopin/FOSMessage/issues/1

**Comment by tgalopin** [comment]
I started to explain what I think the library should be, but I need opinions, thoughts and critics:
https://github.com/tgalopin/FOSMessage

I also need feedbacks of how you currently use the bundle: what you need, what you think that should be implemented, things like that. The new version won't be fully compatible with this version so we can invent new things and resolve new problems.

Thanks by advance!

**Comment by tgalopin** [comment]
I ported almost all the concepts of the current bundle in the library. I changed some things and add others to match with the idea of the library (it's not a bundle anymore after all :) ):

https://github.com/tgalopin/FOSMessage

I am still currently working a lot on the code, don't hesitate to give a hand. For the moment, the next tasks are:

1. Create tests for the current code
2. Implement drivers for Doctrine, Propel, Doctrine ODM
3. Review the current code for mistakes / typos in order to match PSR-2 and have clear comments ;
4. Start to write a doc on how to use the library without Symfony

What is great with this library is that it has only one light dependency (on Doctrine collections), it's very easy to reuse it without any framework.

I didn't implement things like SPAM and security: I didn't implement SPAM for the moment in order to stabilize the library before, I won't implement security in the library as it's the role of the framework / developer.

Please give feedbacks, it's my first shared library, I want to improve it as much as possible :) !

Thanks by advance!

**Comment by SakyaStelios** [comment]
Can I help?

**Comment by tgalopin** [comment]
Yes, don't hesitate! Either by contributing on the library I'm working on or by contributing to this repository (but I can't be sure your pull request will be merged any time soon).

**Comment by smilesrg** [comment]
@tgalopin it's a good idea to write documentation for your library.

**Comment by gperdomor** [comment]
@tgalopin great work... But we need some documentation :D

**Comment by tgalopin** [comment]
I'm working on it, it should be available soon in an early version :) .

**Comment by tgalopin** [comment]
I worked a lot on the library yesterday and today, it's improving a lot while far from being ready for the moment.

If you want to try it and play with it, you can use the examples:

https://github.com/tgalopin/FOSMessage/blob/master/Resources/doc/examples/full-example.php
https://github.com/tgalopin/FOSMessage/tree/master/Resources/doc/examples/entities

The concepts of the library are the same as the bundle, but the code is not exactly the same. I'll write a beginning of documentation as soon as possible (probably this night and tomorrow).

I'm very interested by your opinion about the library and your ideas about it, please don't hesitate to comment, propose ideas and contribute! It's a big project and I really need inputs :) .

**Comment by tgalopin** [comment]
Here is a beginning of documentation:

https://github.com/tgalopin/FOSMessage/tree/master/Resources/doc

Please try the library, I really would like to have inputs!

**Comment by tgalopin** [comment]
@merk : do you think you could put a link to my library in the README of the bundle as the new version in development? It would improve its visibility and people would be aware of its existence.

**Comment by lsmith77** [comment]
see https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/54

**Comment by dbu** [comment]
as per https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/54 we have new maintainers. thanks @tgalopin and @ChristianRiesen!
