### ISSUE TITLE
Adding Favorite Feature

### ISSUE THREAD

**Issue by hyyan** [FriendsOfSymfony/FOSMessageBundle#240]
I was thinking about adding a new feature to make the bundle able to mark thread as favorite and unfavorite .

I will work on this feature and send BR if you think such a feature will be useful guys .

**Comment by tgalopin** [comment]
In the new library, the concept of tags will be implemented in a much more generic way than this one so this issue will be solved. You can read more and follow the work on the new library at https://github.com/FriendsOfSymfony/FOSMessage.
