### ISSUE TITLE
Sending message by user id

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSMessageBundle#243]
Hello,

Is it possible to send message by user id instead of user name ?
I have FOSUserbundle, and I know that the username is unique, but in my website I've set that up to be the email address. And I don't want users to be able to see the email addresses even if it's hidden somewhere in the HTML code.

So how can I manage to do it without enterfering with the FOSUserBundle process ?

**Comment by charafsalmi** [comment]
Could you give us some examples of the way you did it ? Thanks.
