### ISSUE TITLE
fos_message_nb_unread() doesn't match up with getInboxThreads 

### ISSUE THREAD

**Issue by aequasi** [FriendsOfSymfony/FOSMessageBundle#245]
Should these match up? I think getInboxThreads should be able to see replies, even if the user deleted the thread. When you delete an email thread in gmail, and someone replies, you still see the reply.

**edit**: I see in the code that this is supposed to work, but it doesn't seem to work for me.

**Comment by tgalopin** [comment]
I think this is too old, please tell me if it's not.
