### ISSUE TITLE
When I have override the Form & Handler after saving message its gives error 

### ISSUE THREAD

**Issue by jignesh-huskerit** [FriendsOfSymfony/FOSMessageBundle#250]
I got this type of Error while submiting new message after override method used in my Bundle :

ContextErrorException: Catchable Fatal Error: Argument 1 passed to Ims\NotesBundle\Form\Handler\NewThreadMultipleMessageFormHandler::composeMessage() must be an instance of FOS\MessageBundle\FormModel\AbstractMessage, instance of Ims\NotesBundle\Form\Model\NewThreadMultipleMessage given, called in /var/www/html/ims/vendor/friendsofsymfony/message-bundle/FOS/MessageBundle/FormHandler/AbstractMessageFormHandler.php on line 62 and defined in /var/www/html/ims/src/Ims/NotesBundle/Form/Handler/NewThreadMultipleMessageFormHandler.php line 25

help me ...

**Comment by charafsalmi** [comment]
Could you show us the config.xml file ?
