### ISSUE TITLE
so many nesting level exception in event listener

### ISSUE THREAD

**Issue by zhangqianxun** [FriendsOfSymfony/FOSMessageBundle#251]
I put send message code in an event listener, but it seems that there are so many nesting level in this procedure. Because my xdebug output this exception 'Error: Maximum function nesting level of '100' reached, aborting!'. And I found out that '$sender->send($message);' takes the most nesting level, so how can I reduce it? Or should I put the send code in controller only?

**Comment by tgalopin** [comment]
I close this as it's quite old, but if you still have the problem, answer to this issue.
