### ISSUE TITLE
Is possible FOSUserBundle using ORM database and FOSMessageBundle using MongoDB (ODM database)?

### ISSUE THREAD

**Issue by aluzardo** [FriendsOfSymfony/FOSMessageBundle#260]
My question:  Is it possible implement FOSMessageBundle using MongoDB but use an entity user class?

I read the documentation https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/01b-odm-models.md

I need edit the line 

@MongoDB\ReferenceOne(targetDocument="Acme\UserBundle\Document\User")

And reference with an entity Acme\UserBundle\Entity\User. Is it possible?

Thanks

**Comment by tgalopin** [comment]
I don't think it's possible (at least without editing a lot of the bundle internals). Do you still need this to be possible? We are working on a framework agnostic library for user to user messaging features based on the concepts of this bundle (https://github.com/FriendsOfSymfony/FOSMessage), if you need this feature, please open a issue in the tracker and explain your use-case. That would help usedesign something useful for you.

**Comment by stof** [comment]
Well, you cannot directly make reference between the ORM and the ODM, as these are separate systems
