### ISSUE TITLE
Base table or view not found: 1146 Table 'symfony.thread' doesn't exist

### ISSUE THREAD

**Issue by wajaja** [FriendsOfSymfony/FOSMessageBundle#262]
how to rename the table for fosmessagebundle in the db

**Comment by tgalopin** [comment]
Hello @wajaja 

If you need help, please consider to be more polite and to give us a bit more of informations about what you need. How to change a table name associated to an entity is very clear in the official documentation.

And please don't hesitate to use "Hello", "Thank you by advance" and other polite forms you may know.

Have a good day,
Titouan

**Comment by stof** [comment]
The entities are defined in your own code (the bundle only provide mapped superclasses), so you can control the table name exactly like you do for our other entities

**Comment by wajaja** [comment]
Hello to all
thanks you for your answers; the problem is solved, I had not named tables in my entities.
