### ISSUE TITLE
Thread has no field or association named isSpam, ThreadMetadata has no field or association named isDeleted, ThreadMetadata has no field or association named lastMessageDate

### ISSUE THREAD

**Issue by peterculak** [FriendsOfSymfony/FOSMessageBundle#263]
I have followed docs from FOSMessageBundle, installed bundle, configured entities, updated schema and when I try to render messages inbox I get these errors. First i get only 1st one after I fixed that I got 2nd and when fixed that then got 3rd one.

[Semantical Error] line 0, col 132 near 'isSpam = :isSpam': Error: Class Application\MessageBundle\Entity\Thread has no field or association named isSpam 

[Semantical Error] line 0, col 156 near 'isDeleted = :isDeleted': Error: Class Application\MessageBundle\Entity\ThreadMetadata has no field or association named isDeleted 

[Semantical Error] line 0, col 186 near 'lastMessageDate': Error: Class Application\MessageBundle\Entity\ThreadMetadata has no field or association named lastMessageDate 

ThreadMetadata has no field or association named lastParticipantMessageDate

I got it fixed by persisting those fields then errors go away.

**Comment by tgalopin** [comment]
Is it still a problem?

I suspect a mapping issue. Can you copy your application entities here?

**Comment by Mohammadtrabelsi** [comment]
yes i have the same problem:

`
>  [Semantical Error] line 0, col 144 near 'isSpam = :isSpam': Error: Class Application\Sonata\MessageBundle\Entity\Thread has no field or association named isSpam

`
Any one know how to solve it ?

**Comment by tgalopin** [comment]
Hello @Mohammadtrabelsi,

Can you give me your whole error stack? I would like to know what throw the expection.

**Comment by Mohammadtrabelsi** [comment]
Hello !
this is the whole code error :
```
[Semantical Error] line 0, col 144 near 'isSpam = :isSpam': Error: Class Application\Sonata\MessageBundle\Entity\Thread has no field or association named isSpam
500 Internal Server Error - QueryException
1 linked Exception: QueryException »
```

`CRITICAL - Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 144 near 'isSpam = :isSpam': Error: Class Application\Sonata\MessageBundle\Entity\Thread has no field or association named isSpam" at /projet/pivotalpartnersbo/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 `

**Comment by chess-server** [comment]
I had the same issue. I forgot the "extends BaseThread" part on the class definition. 

However, I do have a similar issue now with isDeleted, lastMessageDate etc on ThreadMetadata. Here the extends part is added in my file. A resolution is to add the variables to the local ThreadMetadata file.  

I have no idea why it is working with Thread, but not with ThreadMetadata. The only difference is that Thread implements ThreadInterface, while ThreadMetadata does not implement an interface.

**Comment by sral97** [comment]
I had a similar issue where none of the inherited properties where created as database fields. The solution in my case was to fix all invalid entity mappings in other entities (of which i wasn't even aware of before).

**Comment by ganeshlemoius** [comment]
I got this error.

Exception detected! 
[Semantical Error] line 0, col 70 near 'tm INNER JOIN': Error: Class FOS\MessageBundle\Entity\Thread has no association named metadata
500 Internal Server Error - QueryException
1 linked Exception: QueryException »

[2/2] QueryException: [Semantical Error] line 0, col 70 near 'tm INNER JOIN': Error: Class FOS\MessageBundle\Entity\Thread has no association named metadata   +
[1/2] QueryException: SELECT t FROM FOS\MessageBundle\Entity\Thread t INNER JOIN t.metadata tm INNER JOIN tm.participant p WHERE p.id = :user_id AND t.isSpam = :isSpam AND tm.isDeleted = :isDeleted AND tm.lastMessageDate IS NOT NULL ORDER BY tm.lastMessageDate DESC   +


How to solve this error ?

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue

**Comment by jyyyy** [comment]
did you find the solution please help me

**Comment by hex333ham** [comment]
@jyyyy please provide more information, such as:

* version of Symfony
* version of bundle
* complete error log

**Comment by hex333ham** [comment]
I highly suspect this is a Sonata problem

**Comment by jyyyy** [comment]
actually, i work on a project based on FOSCommentBundle & FOSMessageBundle at the time 
so the problem is on the Thread class
I cannot extend
use FOS\CommentBundle\Entity\Thread as BaseThread;
use FOS\MessageBundle\Model\Thread as BaseThread;
at the same time

when i try to create Thread with another name a error is trigger

**Comment by jyyyy** [comment]
I'm working with Symfony 4

**Comment by hex333ham** [comment]
@jyyyy are you on the latest version? (check your `composer.json` file)

**Comment by jyyyy** [comment]
what do you mean by should be 2.00

**Comment by hex333ham** [comment]
@jyyyy sorry, latest version of the bundle, not Symfony

**Comment by jyyyy** [comment]
yes i'm on the last version of symfony

**Comment by hex333ham** [comment]
@jyyyy what version of `FOSMessageBundle` are you using?

**Comment by jyyyy** [comment]
"friendsofsymfony/comment-bundle": "^2.3",
        "friendsofsymfony/message-bundle": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0",

**Comment by hex333ham** [comment]
@jyyyy cheers

First port of call is to try what @chess-server mentioned:

> I had the same issue. I forgot the "extends BaseThread" part on the class definition.
> 
> However, I do have a similar issue now with isDeleted, lastMessageDate etc on ThreadMetadata. Here the extends part is added in my file. A resolution is to add the variables to the local ThreadMetadata file.
> 
> I have no idea why it is working with Thread, but not with ThreadMetadata. The only difference is that Thread implements ThreadInterface, while ThreadMetadata does not implement an interface.

If you're using what you've said above in the same file together, you've just tried to call both Threads `BaseThread` which might be why the issue is happening.

> use FOS\CommentBundle\Entity\Thread as BaseThread;
> use FOS\MessageBundle\Model\Thread as BaseThread;

**Comment by jyyyy** [comment]
should i add all fields in my custom class!

**Comment by hex333ham** [comment]
@jyyyy without knowing the end result I can't tell you

**Comment by hex333ham** [comment]
closing from inactivity
