### ISSUE TITLE
AddParticipant does not create message metadata

### ISSUE THREAD

**Issue by titouan13** [FriendsOfSymfony/FOSMessageBundle#265]
Hi,

When I add a participant to a thread, it simply creates thread metadata for him/her but no message metadata are created. Then if I want to delete the thread for that specific participant, it triggers an error as "No metadata exists for participant with id %s".

So I have to manually add message metadata with this participant id in order to avoid errors.

**Comment by tgalopin** [comment]
Hum, that is weird. Do you have a bit of code to share?

**Comment by titouan13** [comment]
1 - Use addParticipant() from Thread entity
2 - Use markAsDeleted() from the 'fos_message.deleter' service on the same thread
3 - You will get the error probably due to the call of setIsReadByParticipant (from Model\Message) in Model\Thread.php:213 as no message metadata were added.

To avoid this problem, I manually add message metadata.

This problem was occurring with the version as of May the 19th.

**Comment by tgalopin** [comment]
I investigated this and you should call saveThread from the `fos_message.thread_manager` to synchronize the metadata from your entites (if you specify the second argument as false, it won't flush).

I close but if you need more help, don't hesitate to ask.
