### ISSUE TITLE
FOSUserBundle dependecy

### ISSUE THREAD

**Issue by juanolon** [FriendsOfSymfony/FOSMessageBundle#267]
Hello everyone!
where exactly is FOSUserBundle being used? i have only found `fos_message.recipients_data_transformer` 'til now. 
Which can be replaced, thanks to this PR https://github.com/FriendsOfSymfony/FOSMessageBundle/pull/170/files

anything else to be concerned of?

**Comment by tgalopin** [comment]
Hello @juanolon !

You are right, the only dependance on the FOSUserBundle comes from the data transformer. I created a pull request to add documentation about it (https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/899e286bee7f407db4818c392570ccafb077764a/Resources/doc/99-using-other-user-bundles.md) but it seems there is no maintainer available to merge it.

Please note that this bundle is not maintained for the moment. I'll probably become the maintainer in a few weeks (https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/54) but until then, it's not a good idea to use to bundle in production projects.

If you need more help on how to integrate your custom user system, I can probably help you :) .

**Comment by juanolon** [comment]
Hello @tgalopin 
thanks for the feedback - glad to know, this bundle gets an maintainer :)
see you around
