### ISSUE TITLE
Sending a message programmatically

### ISSUE THREAD

**Issue by BraveFart** [FriendsOfSymfony/FOSMessageBundle#273]
Hello !
I'm trying to reply to a thread programmatically and I'm using the following code to get the thread object with the threadId:

`$thread = $provider->getThread($threadId);`

But I'm getting an AccessDeniedException with : 
> You are not allowed to see this thread

I even tried to get the thread directly with `$thread=$this>threadManager>findThreadById($threadId);`

and looping thru the `$thread->getParticipants()` array and printing the ids of all the participants I can see the Id of the current authenticated participant.

**Comment by tgalopin** [comment]
Hello @BraveFart!

Do you have a logged user in the Symfony context? What do you get if you dump the value of `$this->getUser();` right before your provider call?

**Comment by BraveFart** [comment]
Hi ! And thank you for your reply !
Actually I'm not calling it from inside a controller, I'm using a [Topic](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/master/Resources/docs/TopicSetup.md) class from the [WebSocketBundle](https://github.com/GeniusesOfSymfony/WebSocketBundle)
But I tried all the following ways to get the user object :
```
$user = $this->clientManipulator->getClient($connection);
$participant = $this->participantProvider->getAuthenticatedParticipant();
$sender = $this->context->getToken()->getUser();
```
By printing the ids and the usernames of the objects I can see that they're present and correct !! I tried to compare between these three objects and they do equal each other !!

Now I'm just getting the thread directly with : `$thread = $this->threadManager->findThreadById($threadId);`

and then 
```
$par = $this->isParticipant($thread->getParticipants(), $user);
if ($par) {
$message = $this->composer->reply($thread)
                  ->setSender($par)
                  ->setBody($event["msg"])
                  ->getMessage();
$this->sender->send($message);
.....
```
And this is my isParticipant method :
```
    private function isParticipant(array $participants, $participant)
    {
        foreach ($participants as $par) {
            if ($participant->getId() == $par->getId()) {
                return $par;
            }
        }
        return false;
    }
```

But I'm not really happy with this code !!
Thanks again !

**Comment by tgalopin** [comment]
That's really weird ...

Using the working code, what returns `$thread->isParticipant($this->participantProvider->getAuthenticatedParticipant())` ?

**Comment by BraveFart** [comment]
I just tried that ! And the return value is false !

Another thing ! If I changed the $par parameter of the setSender() which I get from the `$thread->getParticipants()` by the $this->participantProvider->getAuthenticatedParticipant() or other user objects I get the following exception

> [2016-03-20 19:20:06] websocket.ERROR: A new entity was found through the relationship 'AppBundle\Entity\Message#sender' that was not configured to cascade pers
> ist operations for entity: user555. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this
> association in the mapping for example @ManyToOne(..,cascade={"persist"}).

And user555 is the username of the authenticated user !

**Comment by tgalopin** [comment]
`$thread->isParticipant($this->participantProvider->getAuthenticatedParticipant())` should be true: that's the problem. Are you certain the user is a member of the thread? It does not seem so.

For your second problem, I'm not sure in which context you are: are your users saved in a database?

**Comment by tgalopin** [comment]
I close this, but if you still have the problem, don't hesitate to ask.
