### ISSUE TITLE
Cannot instantiate interface FOS\MessageBundle\Provider\ProviderInterface

### ISSUE THREAD

**Issue by Enach** [FriendsOfSymfony/FOSMessageBundle#278]
Hi,

I got an Issue with my subclass user.

![bzf45le](https://cloud.githubusercontent.com/assets/2420221/14297155/c99fb10c-fb7d-11e5-9dc9-ebff93a6b731.png)

I tried with or without implements ParticipantInterface

![screenshot_1](https://cloud.githubusercontent.com/assets/2420221/14297154/c9920e58-fb7d-11e5-90fa-fc4421cade0d.png)

![screenshot_5](https://cloud.githubusercontent.com/assets/2420221/14297153/c991923e-fb7d-11e5-8b56-f5982091697d.png)

And there it is my config.yml
`fos_user:
    db_driver: orm
    firewall_name: main
    user_class: challenkers\UserBundle\Entity\User`

Thank you in advance

**Comment by tgalopin** [comment]
It seems somewhere you are trying to do `new ParticipantInterface`, which is not possible. Can you check your appDevDebugProjectContainer.php file at line 1536? It will probably give you a hint on where the instanciation is done.

**Comment by Enach** [comment]
At line 1536 I got this. So I can't create a new ProviderInterface of FOSMessage, that's it ?

![screenshot_2](https://cloud.githubusercontent.com/assets/2420221/14311554/48737134-fbe8-11e5-8ba0-8f7c9783d7e3.png)

**Comment by tgalopin** [comment]
Oh yes, I misread your first post. What is your FOSMessageBundle configuration? Currently, the container is trying to instanciate a ProviderInterface, which is not possible, and I suspect it comes from the configuration or from a missing default provider.

**Comment by Enach** [comment]
Here there is y fos_message config.yml

![screenshot_3](https://cloud.githubusercontent.com/assets/2420221/14314410/4d7cc18a-fbf7-11e5-9edc-1e8562bd95be.png)

If I add the provider like that : 

![screenshot_4](https://cloud.githubusercontent.com/assets/2420221/14314525/030a8ce4-fbf8-11e5-9be7-6cf78b6a2bc3.png)

I got this :
![screenshot_6](https://cloud.githubusercontent.com/assets/2420221/14314536/131f1884-fbf8-11e5-9913-e04370daae7f.png)
