### ISSUE TITLE
Trouble goingh trough the http_basic form

### ISSUE THREAD

**Issue by ggeorgievgshkk** [FriendsOfSymfony/FOSMessageBundle#281]
I finally managed to install FOSMessageBundle on Symfony3 now when I am trying to start using it, I`m using these two lines of code 

$provider = $this->container->get('fos_message.provider');
$provider->getNbUnreadMessages();

The thing is that the second row invokes a http_basic form with username and password required which I can't get to pass. Where are these two configured? 

I am using DoctrineORM, MySQL, CUSTOM User Entity, Custom Login Form

I am NOT using FOSUserBundle.

Thanks in advance.

**Comment by tgalopin** [comment]
This is probably due to your security configuration. The provider try to access the current user and is probably using your security to log in.

I close this as it is quite old, bu don't hesitate to ask if you still have the problem.
