### ISSUE TITLE
Link: send message to "username"

### ISSUE THREAD

**Issue by Filoz** [FriendsOfSymfony/FOSMessageBundle#284]
Hi, 
I want to add a link in the user profile page to directly send a message to that user (to pre-fill the recipient field)
I read the documentation and the source but I can't find anything like this.
Which can be the best solution to achieve this?

Thankyou

**Comment by tgalopin** [comment]
You should override the default templates (http://symfony.com/doc/current/templating/overriding.html) and display your link as you wish there. You can copy-paste the default templates from `vendor/friends-of-symfony/message/Resources/views` to your `app/Resources/views` directory and change them. Remember that any user object is got from your own application (ie. it is your user object, you probably know the getters available).

If you need more help, don't hesitate to ask.

**Comment by Filoz** [comment]
Hi, 
thank you for your reply!

the only problem is when I have to pre-fill the recipient field... should I override also the new message controller?

**Comment by tgalopin** [comment]
Hello @Filoz,

You can override the default value in the template (http://stackoverflow.com/questions/13916001/set-default-value-of-symfony-2-form-field-in-twig) and therefore set the user you want. However, if you want more control over the behavior of your form, i suggest you indeed to override the controller (or simply make your own and disable the routing of the FOSMessageBundle).

**Comment by josephpepperson** [comment]
Hello @Filoz if you solve the problem could you help me about it.

**Comment by hex333ham** [comment]
I've done this before and it my eyes it's still a relevant question

assigning to me, I'll add this to the docs at some point

**Comment by GuilhemN** [comment]
I'm not fund of wikis on github so I'd prefer updating the docs but I've granted you the admin rights so you can do what you prefer ;)

**Comment by hex333ham** [comment]
@GuilhemN fair enough, more thinking for informal "meta" questions than actual docs, so we don't have to update the version number when answering implementation questions

I'd personally prefer having the actual docs sat next to the bundle from a usability perspective

I'll have a think, cheers for sorting those admin rights again :)

**Comment by hex333ham** [comment]
closing from inactivity
