### ISSUE TITLE
PHP FATAL ERROR use FOS\MessageBundle\Model\ThreadMetadata

### ISSUE THREAD

**Issue by aliel** [FriendsOfSymfony/FOSMessageBundle#287]
Hi

with last merge, i have an error =>
`
PHP Fatal error:  Cannot use FOS\MessageBundle\Model\ThreadMetadata as ThreadMetadata because the name is already in use in MessageBundle/Entity/Thread.php on line 12`

Suspected commit => #286 
https://github.com/FriendsOfSymfony/FOSMessageBundle/commit/d33c18a601173592ded7ccae41e5a818612e4a60#diff-a365cf1835fe7fc524c52bdfcc452db8R10

env : PHP 7.0.10

**Comment by tgalopin** [comment]
That's indeed the issue. I'm going to fix it in a few minutes.

Thanks!
