### ISSUE TITLE
Can not figure out how to disable new message SelfRecipient validator

### ISSUE THREAD

**Issue by charafsalmi** [FriendsOfSymfony/FOSMessageBundle#295]
Hi !

I struggle trying to disable the SelfRecipient validator in a clean fashion.

I tried :

- copying fos' validation.xml file to the appbundle config dir
- writing a new validation.yml file containing a validation without SelfRecipient
- implementing validation_groups

None of this worked. Is there any simple or, at least, clean way to remove the SelfRecipient validator ?

Thank you.

**Comment by charafsalmi** [comment]
I also tried adding this to my services.yml so that I can override it later with an empty class of my own, but it says the validator doesn't exist :
`  fos_message.validator.self_recipient:
    class: FOS\MessageBundle\Validator\SelfRecipientValidator
    arguments: ["@fos_message.participant_provider"]
    tags:
      - { name: validator.constraint_validator, alias: fos_message.validator.self_recipient }
`

**Comment by tgalopin** [comment]
Hello @charafsalmi,

I don't use this bundle on a day-to-day basis so I'm not sure how to do this properly. I think the best way is to follow the validation override promoted by Symfony (http://symfony.com/doc/current/bundles/override.html#override-validation). Is this what you tried?

**Comment by Amacado** [comment]
Any solution yet? Would be interested in..

**Comment by josephpepperson** [comment]
hi @charafsalmi did you find solution?

**Comment by charafsalmi** [comment]
> hi @charafsalmi did you find solution?

Yes ! To give down and to not allow yourself anymore in this kind of situation.

I only continue doing symfony because some of my customers needs it in maintenance, but I will never ever ever recommend this framework to anybody. There are tons of alternatives that are lighter and less uselessly abstract.

70% of my 1 year of intense coding on symfony was struggling to not make my own modules and classes to use this foggy labyrinthine system, ending in situations like this.

Even Wordpress when used as a framework is better on many sides, including scalability, modularity, maintenance, features and documentation.

Please run away. The more devs will drop it, the faster symfony's and FOS's designers will, per haps, stop making complicated things and start doing smart things.

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
