### ISSUE TITLE
FOSMessageBundle Usage Steps

### ISSUE THREAD

**Issue by RymHa** [FriendsOfSymfony/FOSMessageBundle#298]
Hi,
I am new to symfony and I am working on a school project which should include a user to user messaging. Can anyone please guide me through using FOSMessageBundle? 
Should I start implementing new actions in a controller other than the FOSMessageBundle Controller using its predefined functionalities?
I saw many people configuring services.yml what's the utility of that?
I know this is very basic but Thank You.

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
