### ISSUE TITLE
how to retrieve the thread id between two participants

### ISSUE THREAD

**Issue by iometrine** [FriendsOfSymfony/FOSMessageBundle#300]
Hi,

how to retriave the thread id between two participants ?

I would like to retrive this to avoid to create a new thread each time.

Thanks a lot

**Comment by iometrine** [comment]
I did this : 

    public function isExist($user1, $user2)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT tm,mm
                FROM AppBundle:ThreadMetadata tm, AppBundle:MessageMetadata mm 
                WHERE mm.message = tm.thread 
                AND tm.participant=:user and mm.participant=:membre
            ');
        $query->setParameters(array(
            'user' => $user,
            'membre' => $membre,
));
        $tm = $query->getResult();

        foreach ($tm as $thread)
        {
            if($thread instanceof ThreadMetadata)
                return $thread->getThread()->getId();
        }
        return 0;

What do you think ?

**Comment by tgalopin** [comment]
Hello @iometrine,

This seems fine, but you should also select the thread itself (with a join) to avoid unecessary lazy SQL query on  `getThread()` call.

**Comment by iometrine** [comment]
Thank you for your answer.
So i built this two request so i share it 

1/ This request let to test if a disucussion exisit between to users
                SELECT t
                FROM AppBundle:ThreadMetadata t, AppBundle:Message m, AppBundle:MessageMetadata mm 
                WHERE m.thread =t.thread 
                AND m.id = mm.message
                AND t.participant=:user and mm.participant=:membre

2/ This request let to find all discusion from one user
                SELECT mm
                FROM AppBundle:Message m , AppBundle:MessageMetadata mm 
                WHERE mm.message =m.id 
                AND m.sender=:user and mm.participant!=:user  

So now i need just to select the thread itself to avoid lazy SQL :)

Thank you for your help tgalopin, you can close this issue :)

**Comment by tgalopin** [comment]
Thanks for your feedback :) !
