### ISSUE TITLE
Form missing when not using FOSUserBundler

### ISSUE THREAD

**Issue by somecallmetim** [FriendsOfSymfony/FOSMessageBundle#301]
Could not load type "FOS\UserBundle\Form\Type\UsernameFormType"
500 Internal Server Error - InvalidArgumentException

Just setting up this bundle and using it today. I'm adding new functionality to an existing Symfony app and it's just using the base Symfony security stuff (ie Guard and whatnot). I'm hoping I can fix this in my project on my own, but would love to see the docs updated for the next newbie who comes sniffing around. :)

Also would love to see the yaml version of the config files in the docs, although I was able to convert the xml over with a bit of effort.

**Comment by somecallmetim** [comment]
Workaround I came up with for this was basically to install FOSUserBundle and completely set it up with the exception of it's routing file. Cumbersome, but it's the best I got. As things currently stand, they should just flat out make FOSUserBundle a required dependency, imho. Then again, I'm not exactly the god of Symfony developers, so take that for what it's worth.

**Comment by somecallmetim** [comment]
(Side note: thanks for all your incredibly hard work on this free to use software bundle). :D

**Comment by somecallmetim** [comment]
The deeper I get into this, the more issues I'm having due to not using FOSUserBundle. If you can start off with FOSUserBundle, your life will be SOOOO much better. :(

**Comment by somecallmetim** [comment]
Ended up nuking the entire original security system and installing FOSUserBundle. As much as I appreciate all the hard work that went into this bundle, I'm almost wishing I just built my own simple messaging system. Two days of fighting with trying to get this up and running without FOSUserBundle seems like more than a bit of a waste. :-/

**Comment by tgalopin** [comment]
Hello @somecallmetim,

The FOSMessageBundle does not strictly require the FOSUserBundle, there is a documentation guide to use it with your own User bundle: https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/99-using-other-user-bundles.md.

I think your problem if explained in it: https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/99-using-other-user-bundles.md#the-default-form-does-not-work-with-my-user-entity

**Comment by somecallmetim** [comment]
@tgalopin Thanks for the reply. :)

Yes, I started off with that page. I never would have gotten as far as I have without it. I'm a bit fresher now, and I'm going to take another look. 

I didn't link the problem I was having with the solution you posted (pre edit, one assumes). It wasn't an issue, after all, of the form not working it was an issue of the form missing completely. Hence the reason why I turned to installing FOSUserBundle. I assumed the missing form would be in there. And it was. If it weren't for the fact that this resulted in a whole slew of other issues, I'd just stick with that. 

Your reply has given me new confidence to try again. I'm going to tinker with your previous suggestion. I'll post here how it turns out. 

Thanks again for all your hard work. If I can get this working, it'll be an amazing fully featured time saver. :)

**Comment by somecallmetim** [comment]
Still having issues. I'm thinking my services.yml might be the issue. I'm definitely not an expert in either XML or YAML and I've only done some very basic dependency injection before this point. Long story short, I have no idea if what I've got is right or not (and so I suspect the error is likely to originate from here). 

Below is the error message followed by my services.yml configuration. I placed the requisite files in src/AppBundle/Service and updated their namespaces accordingly. 

'''
ClassNotFoundException in appDevDebugProjectContainer.php line 1876:
Attempted to load class "ThreadManager" from namespace "FOS\MessageBundle\EntityManager".
Did you forget a "use" statement for e.g. "FOS\MessageBundle\DocumentManager\ThreadManager" or "FOS\MessageBundle\ModelManager\ThreadManager"?
'''

'''
      app.new_thread_form_type:
          class: AppBundle\Service\NewThreadMessageFormType

      app.new_thread_form_factory:
          class: AppBundle\Service\NewThreadMessageFormFactory
          arguments: [
              'fos_message.new_thread_form.type',
              'form.factory',
              fos_message.new_thread_form.name
              fos_message.new_thread_form.model,
              'doctrine',
              'request']
'''

**Comment by somecallmetim** [comment]
By the way, using the latest version of Symfony 3.2. I probably should have mentioned that earlier...

**Comment by somecallmetim** [comment]
So, I've managed to get to here;

```
      app.new_thread_form_factory:
          class: AppBundle\Service\NewThreadMessageFormFactory
          arguments: [
              '@form.factory',
              '@fos_message.new_thread_form.type',
              'fos_message.new_thread_form.name',
              'fos_message.new_thread_form.model',
              ]
```

I figured out that AbstractFormMessageFormFactory is wanting two services, form.factory and fos_message.new_thread_form.type. The issue now is those last two parameters. 


```
    <argument>%fos_message.new_thread_form.name%</argument>
    <argument>%fos_message.new_thread_form.model%</argument>
```

in your xml example. Trouble is, they're not services and I don't know where the parameter is supposed to come from (in either case). I've found several different flavor's of abstract message classes, assuming the fos_...form.model is looking for some kind of message class as the corresponding variable name $messageClass would seem to indicate, but these clearly can't be used directly. I'm guessing the fos_...form.name parameter is wanting the class name of the form being used, but that's all it is. A guess.

**Comment by somecallmetim** [comment]
@merk @tgalopin @ornicar @jmikola @FabienPennequin @zocimek @EmmanuelVella 

Still having issues getting the services.yml set up correctly (now 3 days in). 

For those of you just tuning in, using Symfony 3.2, not using FOSUserBundle. 

I've spent all day on google and I do feel I've made some progress. Still, the thing doesn't function. :(

Here's where I'm at.

```
      app.new_thread_form_type:
          class: AppBundle\Service\NewThreadMessageFormType
          public: false
          arguments: ['@app.user_to_username_transformer']

      app.new_thread_form_factory:
          class: AppBundle\Service\NewThreadMessageFormFactory
          public: false
          arguments: [
              '@form.factory',
              '@fos_message.new_thread_form.type',
              '%fos_message.new_thread_form.name%',
              '%fos_message.new_thread_form.model%'
              ]
```

Here's the current error.

```
Expected argument of type "string", "AppBundle\Service\NewThreadMessageFormType" given
```

I think my current issue is in app.new_thread_form_type. And I now officially have no idea where to look next. There is a getName() function in NewThreadMessageFormType. Am I supposed to somehow call that in services.yml? Is that even possible?

**Comment by somecallmetim** [comment]
@merk @tgalopin @ornicar @jmikola @FabienPennequin @zocimek @EmmanuelVella

If there's anything I can do to help or even a direction someone could point me in, I'd be super appreciative.

**Comment by somecallmetim** [comment]
Still hoping for a reply :(

**Comment by jawish** [comment]
Here's how to get it work without FOSUserBundle:

1. Create the "UserToUsernameTransformer" class to transform between User instance and username. See [Using other UserBundles](https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/99-using-other-user-bundles.md)
2. Create the service definitions:
```yaml
    app.user_to_username_transformer:
        class: AppBundle\Form\DataTransformer\UserToUsernameTransformer
        arguments: ['@doctrine']
    fos_user.user_to_username_transformer:
        alias: app.user_to_username_transformer
```
3. The "NewThreadMessageFormType" form type class needs to be overridden since it has a hard dependency on FOSUserBundle.
**NewThreadMessageFormType.php:**
```php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use AppBundle\Form\Type\UsernameFormType;

/**
 * Message form type for starting a new conversation.
 */
class NewThreadMessageFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('recipient', UsernameFormType::class, array(
                'label' => 'recipient',
                'translation_domain' => 'FOSMessageBundle',
            ))
            ->add('subject', TextType::class, array(
                'label' => 'subject',
                'translation_domain' => 'FOSMessageBundle',
            ))
            ->add('body', TextareaType::class, array(
                'label' => 'body',
                'translation_domain' => 'FOSMessageBundle',
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'intention' => 'message',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'new_thread_message';
    }
}
```
4. The original "NewThreadMessageFormType" class uses a "UsernameFormType" custom form type from FOSUserBundle to display the recipient field, with the "UserToUsernameTransformer" to transform data as needed. You could add the data transformers straight to the "NewThreadMessageFormType" or create a form type as below.
**UsernameFormType.php:**
```php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use AppBundle\Form\DataTransformer\UserToUsernameTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Form type for representing a UserInterface instance by its username string.
 */
class UsernameFormType extends AbstractType
{
    /**
     * @var UserToUsernameTransformer
     */
    protected $usernameTransformer;

    /**
     * Constructor.
     *
     * @param UserToUsernameTransformer $usernameTransformer
     */
    public function __construct(UserToUsernameTransformer $usernameTransformer)
    {
        $this->usernameTransformer = $usernameTransformer;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer($this->usernameTransformer);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return TextType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_username_type';
    }
}
```

5. Register a new service to inject the "UsernameFormType" with the user transformer.
```yaml
    app.form.type.username:
        class: AppBundle\Form\Type\UsernameFormType
        arguments: ['@app.user_to_username_transformer']
        tags:
            - { name: form.type }
```

6. Finally, update the config.yml file with configuration for fos_message to use the new message form.
```yaml
fos_message:
    db_driver: orm
    thread_class: AppBundle\Entity\Thread
    message_class: AppBundle\Entity\Message
    new_thread_form:
        type: AppBundle\Form\Type\NewThreadMessageFormType
```

That should do it :)

**Comment by somecallmetim** [comment]
This is awesome! Worked like a charm. My sincerest thanks. :D
