### ISSUE TITLE
how to override template & controller

### ISSUE THREAD

**Issue by Ahmed0406** [FriendsOfSymfony/FOSMessageBundle#304]
hello, 
I want to override FOSMessageBundle like FOSUserBundle, 
like this:

```
<?php

namespace AppBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
    /*return multiple Bundle*/
    public function getParent()
    {
        return 'FOSUserBundle' , 'MessageBundle';
    }
}
```

any help?

**Comment by viunyk** [comment]
# routing.yml

# FOS message.
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /answers

# FOS message overrides.
fos_message_thread_new:
    path: /answers/new
    defaults:
        _controller: MarketUserBundle:Message:newThread

fos_message_thread_view:
    path: /answers/{threadId}
    defaults:
        _controller: FOSMessageBundle:Message:thread


And controller

<?php

namespace MarketUserBundle\Controller;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use FOS\MessageBundle\Controller\MessageController as FosMessageController;

/**
 * Class MessageController
 * @package MarketUserBundle\Controller
 */
class MessageController extends FosMessageController
{
    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * Create a new message thread.
     *
     * @return Response
     */
    public function newThreadAction()
    {
        $form = $this->container->get('fos_message.new_thread_form.factory')->create();
        $formHandler = $this->container->get('fos_message.new_thread_form.handler');

        if ($message = $formHandler->process($form)) {
            return new RedirectResponse($this->container->get('router')->generate('fos_message_thread_view', array(
                'threadId' => $message->getThread()->getId(),
            )));
        }

        return $this->container->get('templating')->renderResponse('FOSMessageBundle:Message:newThread.html.twig', array(
            'form' => $form->createView(),
            'data' => $form->getData(),
        ));
    }
}

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
