### ISSUE TITLE
FOSMessage Thread Entity

### ISSUE THREAD

**Issue by mdao032** [FriendsOfSymfony/FOSMessageBundle#305]
Hello, 
Can i use the same Thread Entity for FOSMessage Bundle and FOSComment Bunlde ?
Given the contents are not the same...
Or if you have some solutions, it wil be great for me to know it.

Thank you in advance !

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
