### ISSUE TITLE
Docs not updated or my mistake?

### ISSUE THREAD

**Issue by Zuhayer** [FriendsOfSymfony/FOSMessageBundle#310]
I am using FOSMessageBundle and hope to make it work with my symfony 3.1 project.

I am getting multiple errors:
1) https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/90-sending-a-message-programatically.md Line: Composing a message -> ->setSubject('Stof commented ...)
- Method 'setSubject' not found in \FOS\MessageBundle\MessageBuilder\AbstractMessageBuilder

2) https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/02-basic-usage.md Line: Compose a message  ->addRecipient($clyde)
- Method 'addRecipient' not found in \FOS\MessageBundle\MessageBuilder\AbstractMessageBuilder

I have also failed to find any good tutorials that may guide me. From KNP guys to googling, etc.. 

Kindly share any A-Z guide/article/video/etc if possible.

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
