### ISSUE TITLE
Is it me or is there no way to get the recipient of a message in twig?

### ISSUE THREAD

**Issue by plamenh** [FriendsOfSymfony/FOSMessageBundle#316]
I am trying to get the other party in the conversation in twig in the thread_list or the reply view.

If the other party has started the thread, it's easy. However, when the logged user has sent the message and the other party has not sent anything back, it becomes a problem:

Calling thread.firstMessage.participant returns an error (getParticipant() is not a method). I see there's a getParticipant() function in MessageMetadata class, but I don't know how to access it in twig.

In this case I simply want to get the 'recipient' of the only message in the thread that I have sent. Probably it's something very simple and I would appreciate any help.

Thanks.

**Comment by finkbg** [comment]
Ok, I solved it myself, but the method is rather clumsy. Please, advise, if there's something more straightforward:

First, define a getter for the metadata in Message class:

```
    /**
     * Get the MessageMetadata.
     *
     * @return MessageMetadata
     */
    public function getMetadata()
    {
        return $this->metadata;
    }
```

Then, in twig, take the first metadata entry and its participant:

`{{ thread.firstMessage.metadata|first.participant.name|e }}`

Why the first? Well it seems that the bundle just writes the metadata in that order. First entry defines the recipient as participant and the second the sender.

Haven't tested thoroughly, though.

It all looks ugly as s**t. I hope there's a better way.

**Comment by hex333ham** [comment]
this issue is over two years old and I'm tidying up this bundle, if it's still relevant please re-open the issue
