### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by Gemorroj** [FriendsOfSymfony/FOSMessageBundle#318]
Need add Symfony 4 support

**Comment by hairybobbins** [comment]
For anyone who's interested, I've got the bundle working in Symfony 4 in a very 'hacky' way.
Good for a short-term patch/solution.

See the basic installation instructions on how to get bundle overrides for templates working in Symfony 4 with this, that was the only major hurdle I had after changing the installation requirements and renaming template locations to match Symfony 4.

https://github.com/hairybobbins/FOSMessageBundle/tree/symfony4

**Comment by kubaceg** [comment]
I need it too :) Hacky way from @hairybobbins don't work for me, composer can't resolve paths.

**Comment by kubaceg** [comment]
Hi, from user entity
```
Fatal error: Interface 'FOS\MessageBundle\Model\ParticipantInterface' not found in /var/www/symfony/src/Entity/User/User.php on line 10
```
I'm thinking now that probably after my changes in composer.json (repository + new bundle) and composer install command nothing happens. I must check it once again

**Comment by hairybobbins** [comment]
@kubaceg It looks to me like your application is failing before it reaches composer, it might be worth commenting out that reference then seeing if it works.

**Comment by hairybobbins** [comment]
@kubaceg hey, just realised that `target-dir` is being ignored in the composer.json file due to the deprecation of psr-0, this means that if you move the hacky versions code under the correct directory structure within the bundle (`FOS\MessageBundle`) it will work.

If anyone knows of a way to fix this please let me know, I am not the best when it comes to composer.

**Comment by kubaceg** [comment]
Thanks! I'll try it :)

**Comment by kubaceg** [comment]
It works fine :) only what I have to do was add own entities mapping in yaml + define aliases:

```
    fos_user.user_to_username_transformer:
        alias: App\Service\UserToUsernameTransformer

    FOS\MessageBundle\Composer\Composer: '@fos_message.composer'

    FOS\MessageBundle\Sender\Sender: '@fos_message.sender'
```

**Comment by afranioce** [comment]
@hairybobbins I'm using your fork but it's giving the service error

The "fos_message.provider" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by afranioce** [comment]
It ran when I put the services as public in the class `FOS\MessageBundle\DependencyInjection\FOSMessageExtension.php`

Ex.:
```php
class FOSMessageExtension extends Extension
{
//...
    $container->setAlias('fos_message.message_manager', new Alias($config['message_manager'], true));
//...
}
```

**Comment by ChanOmegaWebDesign** [comment]
@hairybobbins I just submitted a pull request to your fork implementing the fix by @afranioce for all the Aliases.

**Comment by finkbg** [comment]
Setting these to true does not work for me -> Symfony 4.0.8. Any suggestions?

**Comment by ChanOmegaWebDesign** [comment]
![capture](https://user-images.githubusercontent.com/3044553/39065581-1844b52e-4487-11e8-8c69-135eb3470ae3.PNG)
@finkbg This works for me, what errors are you getting?

**Comment by hairybobbins** [comment]
Just seen this thread guys (really wish github had a notifications bar, or if it does I wish I could find it :') )

I've got some time free next monday and over the weekend, so I'll have a look at the fork and fixes you've both suggested @ChanOmegaWebDesign @afranioce 

Cheers!

**Comment by finkbg** [comment]
@ChanOmegaWebDesign Thanks, changing the extend path worked for me. For whatever reason (3.4 legacy?) the extend path in the files was FOSMessageBundle::layout.html.twig and it pointed at the vendor path instead of templates/bundles/....

**Comment by hairybobbins** [comment]
Pull request now approved @ChanOmegaWebDesign

**Comment by finkbg** [comment]
Guys, we are now testing extensively and found a massive issue - basically the App/Entities Message, MessageMetadata, Thread, and ThreadMetadata are ignored by the bundle, so any custom methods are not working. This basically renders it unusable for us. Any suggestions? Thanks.

**Comment by hairybobbins** [comment]
@finkbg Can you provide us with your Message entity?

The only suggestion I can offer without that is to make sure you've included `use FOS\MessageBundle\Entity\Message as BaseMessage;` at the top of your entity, then made sure that the Message entity extends this `class Message extends BaseMessage`

**Comment by hairybobbins** [comment]
@finkbg as @kubaceg has mentioned previously, you might also need to map your entities in your config file

**Comment by finkbg** [comment]
I accidentally deleted the original post:

Basically, it said that the App/Entities did not work. Actually, they are working, we were wrongly trying to use a setter when initially creating the thread with $composer->newThread(). This seems a bit confusing, as $composer->newThread() returns an instance of Entity/Message instead of Entity/Thread. We figured it out.

However, we are having a separate issue when serializing the Thread Entity with JMS Serializer. For some reason the @Expose rules in the App/Entity/Thread are being ignored.

**Comment by GuilhemN** [comment]
Symfony 4 support added in https://github.com/FriendsOfSymfony/FOSMessageBundle/pull/329 😄

**Comment by hex333ham** [comment]
Also to everyone using my fork, I've changed my username to hex333ham (professional reasons), make sure to update your composer accordingly

**Comment by GuilhemN** [comment]
No problem, the offer is still available of course ;)
I sent you an invitation, thanks for taking care of this bundle!

**Comment by methodeprog** [comment]
Great bundle sûre i will give a try.
