### ISSUE TITLE
Multiple non-persisted new entities were found through the given association graph

### ISSUE THREAD

**Issue by neimad25** [FriendsOfSymfony/FOSMessageBundle#319]
Hi,
Everything was perfectly working after the installation. But now I encounter a new error : Multiple non-persisted new entities were found through the given association graph.
_* A new entity was found through the relationship 'CSC\MessageBundle\Entity\MessageMetadata#participant' that was not configured to cascade persist operations for entity: webmaster. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
* A new entity was found through the relationship 'CSC\MessageBundle\Entity\MessageMetadata#participant' that was not configured to cascade persist operations for entity: qqqq. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"})._

But _webmaster_ as _qqqq_ where two users from FOSUser already in database. Why do I need to persist them ?
If I set cascade={"persist"} on entity MessageMetadata, I encounter a new error _Notice: Undefined index: 0000000007694a2d00000000110be6bb_

Could you help me ?

**Comment by TheCelavi** [comment]
I have upgraded symfony from 3.4.2 to 3.4.12.

This was broken, as well as isParticipant() method.

Downgrading to 3.4.2 fixed issue, something new is in Symfony, probably within Doctrine bundle, which breaks this... I can not figure out what is different, it is going to be hard to find out.

**Comment by hex333ham** [comment]
this issue is over a year old and I'm tidying up this bundle, if it's still happening please re-open the issue

**Comment by Muspi** [comment]
Hi, I got same error on Symfony 4.4, any idea to solve this?
