### ISSUE TITLE
FORM TARGETS INSECURE URL

### ISSUE THREAD

**Issue by lihtemyfire** [FriendsOfSymfony/FOSMessageBundle#320]
Hi team FOS,

 I'm running Symfony 3.3 and have the bundle up and working in dev on localhost but once i push it to prod, it won't allow me to send/receive messages. it is giving me the error:

"The page at https://www.xxxxxx.com/messages contains a form which targets an insecure URL http://www.xxxxxx.com/messages"

Has anyone had this problem before? I couldn't find any documentation on it and nothing in the docs about it.. Am i just being daft? Any help to resolve this would be greatly appreciated!!

Thank you. 

ps: attached a screenshot if it helps?

![screen shot 2018-02-01 at 7 53 02 pm](https://user-images.githubusercontent.com/34558650/35741293-711ff9d8-0805-11e8-8a13-e29e821720ca.png)

**Comment by hex333ham** [comment]
old issue, so closing regardless (reply if still a problem)

but this is probably a caching issue

if it still persists, try forcing SSL urls - https://symfony.com/doc/current/security/force_https.html
