### ISSUE TITLE
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating".

### ISSUE THREAD

**Issue by lbcd** [FriendsOfSymfony/FOSMessageBundle#324]
On Symfony 4.0 
Just to share an issue where error message didn't help.

Here was the message: 
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating".

What I have done to solve it => add in `fos_user.yaml`:

    service:
        mailer: fos_user.mailer.twig_swift 

So my complete `fos_user.yaml` is:

    fos_user:
        db_driver: orm # other valid values are 'mongodb' and 'couchdb'
        firewall_name: main
        user_class: App\Entity\User
        service:
             mailer: fos_user.mailer.twig_swift
        from_email:
            address: "%env(resolve:MAILER_USER)%"
            sender_name: "%env(resolve:MAILER_USER)%"

**Comment by thib92** [comment]
I had the same issue.

You need to run `composer install templating` (using Flex).
Then, in the `framework.yaml` file, add the following config :

```yaml
templating:
        engines: ['twig']
```

**Comment by hex333ham** [comment]
needs adding to the documentation somewhere (known issues?)

**Comment by hex333ham** [comment]
added the step to check regardless
