### ISSUE TITLE
fos message alert by mail

### ISSUE THREAD

**Issue by devkbsc** [FriendsOfSymfony/FOSMessageBundle#326]
Hello,
Is there any possbilities to send email notification after the fos message sent?

**Comment by hex333ham** [comment]
@devkbsc yup, you can use the events system to trigger an e-mail function when a message has been posted - https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/06-events.md

integrating this into the bundle would be out of scope

**Comment by devkbsc** [comment]
yes, le ticket est cloturé!
