### ISSUE TITLE
Symfony 4 / v2 / is this bundle obsolete?

### ISSUE THREAD

**Issue by MrQuery** [FriendsOfSymfony/FOSMessageBundle#332]
hi, 
how about tagging a new release version?

The v1.3 is about 2 years old and the master 3 months and has the symfony 4 support.

**Comment by MrQuery** [comment]
yes? no? maybe? is this project dead?

**Comment by Gadgetdude** [comment]
Just bumping this thread, it would be really nice to have a stable release that includes Symfony 4 support.

**Comment by hex333ham** [comment]
@MrQuery @Gadgetdude projects not quite dead yet, I've been handed the reigns and it's something I now have time to work on

I'll add the release tag later on this week, want to do some testing on the current state of the project first

**Comment by hex333ham** [comment]
righty, I've tidied the issue chain and I'll be doing some updates when I have time

**Comment by hex333ham** [comment]
testing complete on 4.0, see #334 for unit/functional/all test results

**Comment by hex333ham** [comment]
moving on to latest version, created documentation for getting setup quickly from what I've just done with 4.0

should work with latest, will update shortly

https://gist.github.com/hex333ham/9fae56fd8f0cdf26f7377a150dc9d72a

**Comment by hex333ham** [comment]
4.1 is fine and those instructions work, for details on automated test results see here - #334

**Comment by hex333ham** [comment]
release created, doing a test in composer now to verify this working - https://github.com/FriendsOfSymfony/FOSMessageBundle/releases/tag/v1.4.0

**Comment by hex333ham** [comment]
nevermind, I forgot a few things (need more coffee), deleting that release

**Comment by hex333ham** [comment]
alright, never try the easy route, creating a specific branch for 1.4 to fix deprecation errors

**Comment by hex333ham** [comment]
this is being moved to version 2.0.0 as I'm going to drop support for Symfony 2 (I can't actually get travis to successfully test on the lowest possible)

**Comment by hex333ham** [comment]
build is passing when removing symfony 2.8 - https://github.com/FriendsOfSymfony/FOSMessageBundle/pull/339

I'll leave this up for a couple of days, see what people think before I go ahead and do it

**Comment by hex333ham** [comment]
I see no objections, merging to master

**Comment by hex333ham** [comment]
merged to master, accidentally created the release (prematurely) so apologies for any notifications occurred from that

I'm now going to close this issue and open a new one for the packagist thing
