### ISSUE TITLE
packagist web hook

### ISSUE THREAD

**Issue by hex333ham** [FriendsOfSymfony/FOSMessageBundle#342]
~~packagist currently can't be updated as due to who owns the repo on there~~

~~not sure who to contact on this one, I will try messaging FOS via the website~~

@GuilhemN any ideas?

**please see latest comment for updates**

**Comment by hex333ham** [comment]
Also just realised I left the composer branch at 2.0-dev, keeping it this way until I can resolve this

**Comment by hex333ham** [comment]
looks like we lost packagist hooks as part of this - https://twitter.com/packagist/status/1037035587453235201?lang=en

going to try e-mailing support

**Comment by hex333ham** [comment]
support came back with:

I've manually triggered an update now, but that won't help in the 
future. So ideally you'll try again to reach out to the maintainer to 
either fix the GitHub integration or pass ownership to someone else who 
can manage this package.

**Comment by hex333ham** [comment]
progress! this morning I managed to get access to packagist for the repo but I think FOS as an org in github won't let me setup auto hooks

for now it has to be done manually, which isn't really an issue for me

I'll see if I can resolve this in future, might be that FOS needs to update their perms for repos

**Comment by GuilhemN** [comment]
I've updated your rights on this repository so you should now be able to set up the hook :)

**Comment by hex333ham** [comment]
@GuilhemN excellent, cheers!

Hook updated, closing this now

**Comment by hex333ham** [comment]
re-opening as I need to create the patch for documentation

doing that tomorrow

**Comment by hex333ham** [comment]
updated docs a little late, oh well, resolving tickets
