### ISSUE TITLE
Symfony 4, Twig 3 and FosMessage 2

### ISSUE THREAD

**Issue by vhrychenko** [FriendsOfSymfony/FOSMessageBundle#358]
Hi. 
I've upgraded my Symfony project from 3 to 4 and I faced an issue with MessageExtension class. 

`In MessageExtension.php line 12:

  Attempted to load class "Twig_Extension" from the global namespace.
  Did you forget a "use" statement?
`

so the problem that Twig_Extension is not compatible with Twig 3, it works only for Twig 2. What I do is rewriting directly in vendor folder the code to TwigExtension base class and it works. The same for Twig_Function at lines 35-38. 

How can I override it on the project level or can you push the fix as a new patch?

**Comment by hex333ham** [comment]
see here for info on updates - https://github.com/FriendsOfSymfony/FOSMessageBundle/issues/351
