### ISSUE TITLE
How to add a custom field to the Thread Entity?

### ISSUE THREAD

**Issue by avaldi** [FriendsOfSymfony/FOSMessageBundle#51]
Hi!

I am trying to add a new field to the `Thread` entity and to display it in the `newThreadMessage` form.

I currently added my field to the entity with its getter and setter, I created a custom `NewThreadMessageFormType` which extends `Ornicar\MessageBundle\FormType\NewThreadMessageFormType` but now I am stuck at this point as I get an error saying:

```
Neither property "foo" nor method "getFoo()" nor method "isFoo()" exists in class 
"Ornicar\MessageBundle\FormModel\NewThreadMessage"
```

I guess I should overload also the `NewThreadModel` class, but in this way I am forced to override the `FormHandler` and `FormFactory` as well.

Is this the right way to go?

Thanks,
Andrea

**Comment by bjsaber** [comment]
Same situation here i want to add field to thread entity but am lost with forms please can any one help and describe this step by step.

**Comment by bjsaber** [comment]
@khepin there's nothing in docs related to this issue, im stack with this please can u help

**Comment by tgalopin** [comment]
@bjsaber You have to extend the `FormHandler/NewThreadMessageFormHandler` and configure the bundle to use it (see https://github.com/FriendsOfSymfony/FOSMessageBundle/blob/master/Resources/doc/99-config-reference.md#configuration-reference, especially the configuration key `new_thread_form.handler`).

You will probably also want to edit the FormType to add fields, you can use the configuration key `new_thread_form.type` and extends `FormType\NewThreadMessageFormType`.

**Comment by bjsaber** [comment]
@tgalopin thanks for your help i did just like u said and i have declared my new forms as services and changed my conig as well:
`services:
    message.type.new_thread_form:
        class: MessageBundle\FormType\NewThreadMultipleMessageFormType
    message.message_bundle.form_handler:
        class: MessageBundle\FormHandler\NewThreadMultipleMessageFormHandler
        arguments: [@request, @fos_message.composer, @fos_message.sender, @fos_message.participant_provider]
        scope: request`
but now i get this error:

>  Attempted to call an undefined method named "setThreadLabel" of class "FOS\MessageBundle\MessageBuilder\NewThreadMessageBuilder".
500 Internal Server Error - UndefinedMethodException 

here's my form handler:
`<?php
namespace MessageBundle\FormHandler;

use FOS\MessageBundle\FormHandler\NewThreadMultipleMessageFormHandler as BaseFormHandler;
use FOS\MessageBundle\FormModel\AbstractMessage;
use MessageBundle\FormModel\NewThreadMultipleMessage;

/**
 * Form handler for multiple recipients support
 *
 * @author Łukasz Pospiech <zocimek@gmail.com>
 */
class NewThreadMultipleMessageFormHandler extends BaseFormHandler
{
    public function composeMessage(AbstractMessage $message)
    {
        if (!$message instanceof NewThreadMultipleMessage) {
            throw new \InvalidArgumentException(sprintf('Message must be a NewThreadMultipleMessage instance, "%s" given', get_class($message)));
        }

        return $this->composer->newThread()
            ->setSubject($message->getSubject())
            ->addRecipients($message->getRecipients())
            ->setSender($this->getAuthenticatedParticipant())
            ->setBody($message->getBody())
            ->setThreadLabel($message->getThreadLabel())
            ->getMessage();
    }
}`
and my form type:
`<?php
namespace MessageBundle\FormType;

use Symfony\Component\Form\FormBuilderInterface;
use FOS\MessageBundle\FormType\NewThreadMessageFormType as BaseType;
/**
 * Message form type for starting a new conversation with multiple recipients
 *
 * @author Łukasz Pospiech <zocimek@gmail.com>
 */
class NewThreadMultipleMessageFormType extends BaseType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('recipients', 'recipients_selector')
            ->add('subject', 'text')
            ->add('body', 'textarea')
            ->add('threadLabel', 'entity',array(
                'class' =>  'MessageBundle\Entity\ThreadLabel',
                'property' => 'name',
                'multiple'  =>   false,
                'placeholder' => 'Choose an option'
            ))
        ;
    }

    public function getName()
    {
        return 'fos_message_new_multiperson_thread';
    }
}`

**Comment by manuelLandreau** [comment]
Have you defined your own NewThreadMessage class ?

```
fos_message:
    ...
    new_thread_form:
        type:       YourBundle\Form\NewThreadMessageFormType // Custom formType
        handler:    your_bundle.message.form_handler // Custom service
        model:      YourBundle\Entity\NewThreadMessage // Custom medel
```
