### ISSUE TITLE
Sending MP with the service

### ISSUE THREAD

**Issue by remontees** [FriendsOfSymfony/FOSMessageBundle#82]
When I send a MP with the services :
    
    $composer = $this->get('fos_message.composer');
    $sender = $this->get('fos_message.sender');

Users cannot recieve its because the last_participant_message_date in message_thread_metadata is empty.

Here is my code for information:

    $composer = $this->get('fos_message.composer');
            $sender = $this->get('fos_message.sender');
            
            foreach($reportage->getAuteurs() as $auteur)
            {
                $message = $composer->newThread()
                    ->setSender($this->container->get('security.context')->getToken()->getUser())
                    ->addRecipient($auteur)
                    ->setSubject('blah')
                    ->setBody("blah blah.")
                    ->getMessage();
                
                $sender->send($message->getMessage());
            }

Thanks a lot to fix this bug,

remontees

**Comment by tgalopin** [comment]
@Miliooo really great feedback, thanks! I'll keep it in mind for the new version.
